// src/constants/roles.ts
export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ARTIST_MANAGER: "artist_manager",
  ARTIST: "artist",
};

export const ROLE_PERMISSIONS = {
  USER_LIST: [ROLES.SUPER_ADMIN],
  USER_CREATE: [ROLES.SUPER_ADMIN],
  USER_UPDATE: [ROLES.SUPER_ADMIN],
  USER_DELETE: [ROLES.SUPER_ADMIN],

  ARTIST_LIST: [ROLES.SUPER_ADMIN, ROLES.ARTIST_MANAGER],
  ARTIST_CREATE: [ROLES.ARTIST_MANAGER],
  ARTIST_UPDATE: [ROLES.ARTIST_MANAGER],
  ARTIST_DELETE: [ROLES.ARTIST_MANAGER],
  ARTIST_IMPORT_EXPORT: [ROLES.ARTIST_MANAGER],

  SONG_LIST: [ROLES.SUPER_ADMIN, ROLES.ARTIST_MANAGER, ROLES.ARTIST],
  SONG_CREATE: [ROLES.ARTIST],
  SONG_UPDATE: [ROLES.ARTIST],
  SONG_DELETE: [ROLES.ARTIST],
};
